# Generated by Django 6.1.1 on 2026-09-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.BooleanField()),
                ('taxpayer_tax_id', models.CharField(max_length=9)),
                ('generation', models.PositiveSmallIntegerField()),
                ('number', models.CharField(max_length=100, unique=True)),
                ('system_id', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('production', 'taxpayer_tax_id', 'generation'), name='verifactu_unique_generation')],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveBigIntegerField()),
                ('object_id', models.CharField(max_length=255)),
                ('operation', models.CharField(choices=[('Alta', 'Alta'), ('Anulacion', 'Anulacion')], max_length=9)),
                ('amendment', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(max_length=60)),
                ('issue_date', models.DateField()),
                ('generated_at', models.DateTimeField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('xml', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('accepted_with_errors', 'Accepted With Errors'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('error_code', models.PositiveIntegerField(null=True)),
                ('error_description', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='django_verifactu.installation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'indexes': [models.Index(fields=['installation', 'status', 'position'], name='django_veri_install_5ea2ff_idx'), models.Index(fields=['invoice_number', 'issue_date'], name='django_veri_invoice_00e1a1_idx'), models.Index(fields=['content_type', 'object_id'], name='django_veri_content_d412a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('installation', 'position'), name='verifactu_unique_position')],
            },
        ),
    ]
