# Generated by Django 6.1.1 on 2026-09-28 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_verifactu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_flight', models.CharField(max_length=11, null=True, unique=True)),
                ('incident', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('outcome', models.CharField(choices=[('sending', 'Sending'), ('answered', 'Answered'), ('fault', 'Fault'), ('not_delivered', 'Not Delivered'), ('unknown', 'Unknown')], default='sending', max_length=20)),
                ('csv', models.CharField(blank=True, max_length=100)),
                ('wait_seconds', models.PositiveIntegerField(null=True)),
                ('error_code', models.PositiveIntegerField(null=True)),
                ('response', models.TextField(blank=True)),
                ('installation', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='django_verifactu.installation')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='SubmissionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Correcto', 'Correcto'), ('AceptadoConErrores', 'AceptadoConErrores'), ('Incorrecto', 'Incorrecto')], max_length=20, null=True)),
                ('error_code', models.PositiveIntegerField(null=True)),
                ('error_description', models.TextField(blank=True)),
                ('duplicate_status', models.CharField(choices=[('Correcta', 'Correcta'), ('AceptadaConErrores', 'AceptadaConErrores'), ('Anulada', 'Anulada')], max_length=20, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='django_verifactu.record')),
                ('submission', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='django_verifactu.submission')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['installation', 'created_at'], name='django_veri_install_5efd6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionline',
            constraint=models.UniqueConstraint(fields=('submission', 'record'), name='verifactu_unique_line'),
        ),
    ]
